version: '3'
services:

  #Python Service
  app:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    image: app
    container_name: yandere_bot_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: yandere_bot_app
      SERVICE_TAGS: dev
    working_dir: /var/app
    volumes:
      - ./src:/var/app
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - app-network

  migrator:
      image: app
      command: ["./wait-for-it.sh", "db:6306", "-t", "3", "--", "orator", "migrate", "-c", "db.py", "-f"]
      volumes:
        - ./src:/var/app
      networks:
        - app-network
      depends_on:
        - db

  #MySQL Service
  db:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password --init-file /var/www/scripts/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: strong_P4ssword!
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql_yandere
    ports:
      - "6306:3306"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/init.sql:/var/www/scripts/init.sql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge